apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon       Off
        Flush        1
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Tag          kube.*
        Mem_Buf_Limit 5MB

    [OUTPUT]
        Name         stdout
        Match        *
