apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - resource-limits.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
