apiVersion: v1
kind: LimitRange
metadata:
  name: prod-app-resource-limits
  namespace: prod-apps
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
